# Generated by Django 6.0.7 on 2026-07-19 13:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSuppression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('reason', models.CharField(choices=[('complaint', 'complaint'), ('unsubscribe', 'unsubscribe'), ('bounce', 'bounce'), ('manual', 'manual')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(max_length=7)),
                ('sign_requests', models.IntegerField(default=0)),
                ('ocr_pages', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
            ],
        ),
    ]
