# Generated by Django 6.0.7 on 2026-07-19 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usagecounter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_counters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='usagecounter',
            constraint=models.UniqueConstraint(fields=('user', 'period'), name='uniq_usage_user_period'),
        ),
    ]
