# Generated by Django 6.0.7 on 2026-07-19 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['user', 'status'], name='jobs_job_user_id_ec4047_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['document'], name='jobs_job_documen_8eac86_idx'),
        ),
    ]
