# Generated by Django 6.0.7 on 2026-08-01 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usagecounter_heavy_ops_alter_usagecounter_user_and_more'),
        ('documents', '0003_document_expires_at_document_guest_session_and_more'),
        ('jobs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='guest_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.guestsession'),
        ),
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['guest_session', 'status'], name='jobs_job_guest_s_cb5362_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('guest_session__isnull', True), ('user__isnull', False)), models.Q(('guest_session__isnull', False), ('user__isnull', True)), _connector='OR'), name='job_exactly_one_principal'),
        ),
    ]
