# Generated by Django 6.0.7 on 2026-08-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_guest_session_alter_job_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='error_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
