# Generated by Django 6.0.7 on 2026-08-02 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emailsuppression_email_hash'),
        ('documents', '0005_partial_library_indexes'),
        ('jobs', '0004_job_error_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['user', '-created_at'], name='job_user_recent'),
        ),
    ]
