# Generated by Django 6.0.7 on 2026-08-02 03:52

import apps.esign.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_document_expires_at_document_guest_session_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(choices=[('signer', 'Signer'), ('approver', 'Approver'), ('viewer', 'Viewer'), ('cc', 'Cc')], default='signer', max_length=16)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('notified', 'Notified'), ('viewed', 'Viewed'), ('consented', 'Consented'), ('completed', 'Completed'), ('declined', 'Declined')], default='pending', max_length=16)),
                ('token', models.CharField(db_index=True, default=apps.esign.models.new_token, max_length=64, unique=True)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('consent_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('consent_user_agent', models.CharField(blank=True, max_length=500)),
                ('decline_reason', models.TextField(blank=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='SavedSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('signature', 'Signature'), ('initials', 'Initials')], default='signature', max_length=16)),
                ('method', models.CharField(choices=[('draw', 'Draw'), ('type', 'Type'), ('upload', 'Upload')], default='draw', max_length=16)),
                ('storage_key', models.CharField(max_length=500)),
                ('typed_text', models.CharField(blank=True, max_length=100)),
                ('font', models.CharField(blank=True, max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_default', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='SignRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('completed', 'Completed'), ('declined', 'Declined'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='draft', max_length=16)),
                ('envelope_code', models.CharField(default=apps.esign.models.new_envelope_code, max_length=16, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_every_days', models.PositiveSmallIntegerField(default=3)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('final_key', models.CharField(blank=True, max_length=500)),
                ('certificate_key', models.CharField(blank=True, max_length=500)),
                ('final_sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_requests', to='documents.document')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sign_requests', to=settings.AUTH_USER_MODEL)),
                ('source_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sign_requests', to='documents.documentversion')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SignField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page', models.PositiveIntegerField(default=0)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('w', models.FloatField()),
                ('h', models.FloatField()),
                ('type', models.CharField(choices=[('signature', 'Signature'), ('initials', 'Initials'), ('date_signed', 'Date Signed'), ('text', 'Text'), ('checkbox', 'Checkbox')], default='signature', max_length=16)),
                ('required', models.BooleanField(default=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('value', models.TextField(blank=True)),
                ('image_key', models.CharField(blank=True, max_length=500)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='esign.recipient')),
                ('sign_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='esign.signrequest')),
            ],
            options={
                'ordering': ('page', 'y', 'x'),
            },
        ),
        migrations.AddField(
            model_name='recipient',
            name='sign_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='esign.signrequest'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('created', 'Created'), ('sent', 'Sent'), ('opened', 'Opened'), ('consented', 'Consented'), ('field_filled', 'Field Filled'), ('signed', 'Signed'), ('approved', 'Approved'), ('declined', 'Declined'), ('reminder_sent', 'Reminder Sent'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('completed', 'Completed'), ('seal_applied', 'Seal Applied'), ('downloaded', 'Downloaded')], max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('prev_hash', models.CharField(blank=True, max_length=64)),
                ('event_hash', models.CharField(blank=True, max_length=64)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='esign.recipient')),
                ('sign_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='esign.signrequest')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='signrequest',
            index=models.Index(fields=['owner', 'status'], name='esign_signr_owner_i_00ac0a_idx'),
        ),
    ]
