# Generated by Django 6.0.7 on 2026-08-02 06:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('completed', 'Completed'), ('declined', 'Declined'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('canceled_by_abuse', 'Canceled By Abuse')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='AbuseReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abuse_reports', to='esign.recipient')),
                ('sign_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abuse_reports', to='esign.signrequest')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
