# Generated by Django 6.0.7 on 2026-08-02 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_sender(apps, schema_editor):
    """Existing envelopes learn who sent them, from the FK they still have."""
    SignRequest = apps.get_model("esign", "SignRequest")
    for row in SignRequest.objects.select_related("owner").iterator():
        if row.owner_id and not row.sender_email:
            row.sender_email = row.owner.email
            row.sender_name = row.owner.display_name or ""
            row.save(update_fields=["sender_email", "sender_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_expires_at_document_guest_session_and_more'),
        ('esign', '0002_alter_signrequest_status_abusereport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='signrequest',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='signrequest',
            name='sender_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='signrequest',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sign_requests', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='signrequest',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sign_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_sender, migrations.RunPython.noop),
    ]
