# Generated by Django 6.0.7 on 2026-08-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0003_sign_request_survives_its_sender'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['sign_request', 'created_at'], name='audit_request_created'),
        ),
    ]
