# Generated by Django 6.0.7 on 2026-08-02 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_partial_library_indexes'),
        ('esign', '0004_hot_query_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='signrequest',
            index=models.Index(fields=['owner', '-created_at'], name='sign_owner_recent'),
        ),
    ]
