# Generated by Django 6.0.7 on 2026-07-19 13:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('processing', 'Processing'), ('error', 'Error')], default='processing', max_length=12)),
                ('page_count', models.IntegerField(default=0)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('starred', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('trashed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.IntegerField()),
                ('storage_key', models.CharField(max_length=512)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('page_count', models.IntegerField(default=0)),
                ('sha256', models.CharField(max_length=64)),
                ('label', models.CharField(default='Version', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-seq'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
