# Generated by Django 6.0.7 on 2026-08-02 09:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emailsuppression_email_hash'),
        ('documents', '0003_document_expires_at_document_guest_session_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='documents_d_owner_i_c769e8_idx',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='documents_d_guest_s_4303d3_idx',
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', 'trashed_at', '-updated_at'], name='doc_owner_trash_updated'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['guest_session', 'trashed_at', '-updated_at'], name='doc_guest_trash_updated'),
        ),
    ]
