# Generated by Django 6.0.7 on 2026-08-02 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emailsuppression_email_hash'),
        ('documents', '0004_hot_query_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='doc_owner_trash_updated',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='doc_guest_trash_updated',
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(condition=models.Q(('trashed_at__isnull', True)), fields=['owner', '-updated_at'], name='doc_owner_live_updated'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(condition=models.Q(('trashed_at__isnull', True)), fields=['guest_session', '-updated_at'], name='doc_guest_live_updated'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(condition=models.Q(('trashed_at__isnull', False)), fields=['owner', '-trashed_at'], name='doc_owner_trashed'),
        ),
    ]
